# Disable rules that shouldn't be set for Marp Markdown

# Enforces asterisk as unordered list item marker
MD004: false
# Force lines to be under 80 characters
MD013: false
# Require blank lines around lists
MD032: false
# Disallow inline HTML
MD033: false
# Require first line to be a top level header
MD041: false
# Require images to have alt text
MD045: false
